# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='policy.Policy'),
            preserve_default=False,
        ),
    ]
